Merged multiple stderr echo(s)

diff --git a/songd b/songd
--- a/songd
+++ b/songd
@@ -37,8 +37,7 @@ if (( $# > 0 )); then
             exit $?
             ;;
         * )
-            (>&2 echo Error in parsing "$1")
-            (>&2 echo Aborting)
+            (>&2 echo Error in parsing "$1"; echo Aborting)
             exit 1 ;;
     esac
 
diff --git a/songd-edit b/songd-edit
--- a/songd-edit
+++ b/songd-edit
@@ -38,8 +38,7 @@ if (( $# > 0 )); then
                 index="$2"
                 shift; shift ;;
             * )
-                (>&2 echo Error in parsing "$1")
-                (>&2 echo Aborting)
+                (>&2 echo Error in parsing "$1"; echo Aborting)
                 exit 1 ;;
         esac
     done
@@ -50,8 +49,7 @@ if (( $# > 0 )); then
 
     # Check if the index provided exceeds max value
     if (( $index > $( wc -l "$DATA" | cut -d' ' -f1 ) )); then
-        (>&2 echo The index you provided exceeds the maximum index)
-        (>&2 echo Please provide a valid index)
+        (>&2 echo The index you provided exceeds the maximum index; echo Please provide a valid index)
         exit 1
     fi
 
diff --git a/songd-field b/songd-field
--- a/songd-field
+++ b/songd-field
@@ -38,8 +38,7 @@ if (( $# > 0 )); then
                 showHelp 5
                 exit 0 ;;
             * )
-                (>&2 echo Error in parsing "$1")
-                (>&2 echo Aborting)
+                (>&2 echo Error in parsing "$1"; echo Aborting)
                 exit 1 ;;
         esac
     done
